### ISSUE TITLE
Fix Needed For Koyeb

### ISSUE THREAD

**Issue by Ryuto77** [ThiruXD/ATL-Rename-Bot#2]
Instance allocated in nomad
Service mesh is not ready yet
Instance is starting
Service mesh is propagated
ERROR: no command to run your application: add a run command in your Service configuration or create a Procfile in your git repository. Check https://koyeb.com/e/run-command for more details.
ERROR: no command to run your application: add a run command in your Service configuration or create a Procfile in your git repository. Check https://koyeb.com/e/run-command for more details.
Instance terminated in nomad
Instance allocated in nomad
Service mesh is not ready yet
Instance is starting
Service mesh is propagated
ERROR: no command to run your application: add a run command in your Service configuration or create a Procfile in your git repository. Check https://koyeb.com/e/run-command for more details.
Instance terminated in nomad

**Comment by ThiruXD** [comment]
i will fix...

**Comment by ThiruXD** [comment]
as soon as possible
